[package]
name = "crossbeam-epoch"
version = "0.1.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam-epoch"
homepage = "https://github.com/crossbeam-rs/crossbeam-epoch"
documentation = "https://docs.rs/crossbeam-epoch"
description = "Epoch-based garbage collection"

[features]
nightly = []
strict_gc = []

[dependencies]
scopeguard = "0.3"
lazy_static = "0.2"
boxfnonce = "0.0.3"
arrayvec = "0.4"
crossbeam-utils = "0.1"

[dev-dependencies]
rand = "0.3"
